blank_issues_enabled: true
contact_links:
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
address By:
Created By:
description: 'GitHub action to create custom status'
branding:
  icon: 'check-square'
  color: 'black'
runs:
  using: 'docker'
  image: 'docker://geekodour/ghcs:0.0.4'
 -state: 'Verify fixed'
